//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationControls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CssClasses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CssClasses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValidationControls.Resources.CssClasses", typeof(CssClasses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alphanumeric.
        /// </summary>
        internal static string alphanumeric {
            get {
                return ResourceManager.GetString("alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        internal static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digits.
        /// </summary>
        internal static string digits {
            get {
                return ResourceManager.GetString("digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to letter.
        /// </summary>
        internal static string letter {
            get {
                return ResourceManager.GetString("letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notag.
        /// </summary>
        internal static string notag {
            get {
                return ResourceManager.GetString("notag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urlFriendly.
        /// </summary>
        internal static string urlFriendly {
            get {
                return ResourceManager.GetString("urlFriendly", resourceCulture);
            }
        }
    }
}
